In [1]:
import numpy as np

In [7]:
my_list = [1, 2, 3]

In [3]:
type(my_list)

list

In [4]:
np_list = np.array(my_list)

In [6]:
np_list

array([1, 2, 3])

In [8]:
type(np_list)

numpy.ndarray

In [16]:
np.arange(1, 10, 2)
# numpy.arnage create List

array([1, 3, 5, 7, 9])

In [24]:
np.zeros(shape=(5, 5))
# numpy.zeros create Float Type Variables, filled with 0
    # shape=(height, width)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(shape=(5, 5))
# numpy.zeros create Float Type Variables, filled with 1
    # shape=(height, width)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.random.seed(101)
# np.random은 난수를 반환해줍니다.
# 이 경우 seed(지정 숫자)를 사용하면 항상 정해진 난수를 받을 수 있습니다.

arr = np.random.randint(0, 100, 10)
# 첫 번째 실행에서는 array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])이 나올 것입니다.

In [40]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
arr2 = np.random.randint(0, 100, 10)
# 두 번째 실행에서는 array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])이 나올 것입니다.

In [33]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [51]:
#===========지금부터 몇 가지 유용한 커맨드에 대해서 안내하겠습니다.===========#

In [52]:
arr.max() # 최댓값

95

In [53]:
arr.argmax() # 최댓값의 인덱스

0

In [54]:
arr.min() # 최솟값

9

In [55]:
arr.argmin() # 최솟값의 인덱스

7

In [56]:
arr.mean() # 평균값

60.8

In [57]:
arr.shape # 벡터의 크기를 보여주며, (10, 0) 은 가로 10 세로 0의 배열

(10,)

In [58]:
# np.random.randint(0, 100, 10)으로 생성한 길이 10의 배열은 다음과 같이 2 * 5 로 변경이 가능 

arr.reshape((2, 5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [59]:
#=========== Quiz.===========#

In [85]:
mat = np.arange(0, 100).reshape(10, 10)

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [88]:
mat[0:2, 0:2]

array([[ 0,  1],
       [10, 11]])

In [89]:
mat[:,0:2].reshape(2, 10)

array([[ 0,  1, 10, 11, 20, 21, 30, 31, 40, 41],
       [50, 51, 60, 61, 70, 71, 80, 81, 90, 91]])

In [90]:
mat[:,5:7].reshape(2, 10)

array([[ 5,  6, 15, 16, 25, 26, 35, 36, 45, 46],
       [55, 56, 65, 66, 75, 76, 85, 86, 95, 96]])

In [91]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
mat[1, :] = 0

In [93]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])