In [20]:
import numpy as np
from numpy import genfromtxt

In [21]:
real_data = genfromtxt(
    '../../DATA/bank_note_data.txt',
    delimiter=','                     # 기본 특징점들을 콤마(,)를 기준으로 분할
)
real_data
# [[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ]]
#     feature,   feature,  feature,   feature,    label - 0 means fake paper money
#                                                       - 1 means real paper money

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [22]:
labels = real_data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [23]:
features = real_data[:, :4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [24]:
X = features    # 대문자 X는 일반적으로 2D 행렬 의미
y = labels      # 소문자 Y는 단일 행렬 백터 의미

In [25]:
from sklearn.model_selection import train_test_split

#########################################################################
## `특징점들`을 레이블들을 훈련용과 테스트 세트로 분류해주는 라이브러리 ##
## 이 라이브러리는 자동으로 정렬을 해줘서 레이블들이 섞이지 않도록 제어 ##
#########################################################################

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

##########################################################################################################################
## test_size에 할당된 0.33(33%)에 해당하는 숫자만큼의 특징점들은 X_test가 되고 그 숫자만큼의 레이블들은 y_test가 됩니다.  ##
## `항상 동일한 순서`로 무작위 정렬되기 위한 시드값으로써 random_state에 42를 할당해줍니다.                               ##
###########################################################################################################################

In [27]:
print(len(X_train), len(X_test), len(X))
print(len(y_train), len(y_test), len(y))

919 453 1372
919 453 1372


In [28]:
print(X_test.max(), X_test.min())

#########################################################################################################
## 만약, 최댓값이 100만 정도에 최솟값이 -13 정도라면 특징점이 몇 배 이상 벗어난 것이라고 할 수 있습니다. ##
## 따라서, 꼭 최댓값과 최솟값을 확인하는 습관을 길러야 합니다.                                           ##
##########################################################################################################

17.1116 -13.2869


In [29]:
from sklearn.preprocessing import MinMaxScaler

################################################################################################
## 모든 특징점 데이터들이 특정 범위로 좁혀지게 되어서 Neural Network 분석을 하기 용이해지니다. ##
###############################################################################################

In [30]:
scalar_object = MinMaxScaler()

In [31]:
scalar_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [32]:
scaled_X_train = scalar_object.transform(X_train)
scaled_X_test = scalar_object.transform(X_test)

In [33]:
print(scaled_X_train.max(), scaled_X_train.min())
print(scaled_X_test.max(), scaled_X_test.min())

1.0000000000000002 0.0
1.02679563427227 -0.0010694864308909147


In [34]:
from keras.models import Sequential
from keras.layers import Dense

In [35]:
model = Sequential()
model.add(Dense(units=4, input_dim=4, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

In [36]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [38]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.6776 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6662 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6567 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6479 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6356 - acc: 0.5658
Epoch 6/50
 - 0s - loss: 0.6205 - acc: 0.5974
Epoch 7/50
 - 0s - loss: 0.6055 - acc: 0.6561
Epoch 8/50
 - 0s - loss: 0.5898 - acc: 0.7280
Epoch 9/50
 - 0s - loss: 0.5725 - acc: 0.7639
Epoch 10/50
 - 0s - loss: 0.5545 - acc: 0.7780
Epoch 11/50
 - 0s - loss: 0.5355 - acc: 0.8172
Epoch 12/50
 - 0s - loss: 0.5152 - acc: 0.8292
Epoch 13/50
 - 0s - loss: 0.4953 - acc: 0.8368
Epoch 14/50
 - 0s - loss: 0.4758 - acc: 0.8433
Epoch 15/50
 - 0s - loss: 0.4573 - acc: 0.8466
Epoch 16/50
 - 0s - loss: 0.4396 - acc: 0.8596
Epoch 17/50
 - 0s - loss: 0.4236 - acc: 0.8672
Epoch 18/50
 - 0s - loss: 0.4090 - acc: 0.8694
Epoch 19/50
 - 0s - loss: 0.3958 - acc: 0.8727
Epoch 20/50
 - 0s - loss: 0.3833 - acc: 0.8749
Epoch 21/50
 - 0s - loss: 0.3720 - acc: 0.8781
Epoch 22/50
 - 0s - lo

In [41]:
model.metrics_names

['loss', 'acc']

In [42]:
from sklearn.metrics import confusion_matrix, classification_report

In [43]:
predictions = model.predict_classes(scaled_X_test)
confusion_matrix(y_test, predictions)

array([[252,   5],
       [ 22, 174]], dtype=int64)

In [44]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.92      0.98      0.95       257
        1.0       0.97      0.89      0.93       196

avg / total       0.94      0.94      0.94       453



In [46]:
## Save Model
model.save('mysupermodel.h5')

In [47]:
## Load Model
from keras.models import load_model

new_model = load_model('mysupermodel.h5')

In [48]:
new_model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    